// Sample gallery stickers (using emoji placeholders for demo)
const galleryStickers = [
    { id: 1, prompt: "cute neko girl with pink hair", emoji: "🐱👧💕" },
    { id: 2, prompt: "samurai warrior with cherry blossoms", emoji: "⚔️🌸" },
    { id: 3, prompt: "magical girl with sparkling wand", emoji: "✨👧⭐" },
    { id: 4, prompt: "cyberpunk anime hacker", emoji: "🤖💻🔥" },
    { id: 5, prompt: "gothic lolita vampire", emoji: "🧛‍♀️🖤🎀" },
    { id: 6, prompt: "mecha pilot with energy sword", emoji: "🤖⚡🗡️" },
    { id: 7, prompt: "schoolgirl with magical fox familiar", emoji: "🦊👧📚" },
    { id: 8, prompt: "space princess with galaxy hair", emoji: "👸🌌✨" },
    { id: 9, prompt: "ninja girl with shurikens", emoji: "🥷⭐" },
    { id: 10, prompt: "idol singer with microphone", emoji: "🎤💖" },
    { id: 11, prompt: "demon girl with horns", emoji: "😈🔥" },
    { id: 12, prompt: "angel warrior with wings", emoji: "👼⚔️" }
];

let displayedStickers = 6;
let currentGeneratedSticker = null;

// Initialize page
document.addEventListener('DOMContentLoaded', function() {
    loadGallery();
    setupSmoothScrolling();
    setupMobileMenu();
});

// Smooth scrolling for navigation
function setupSmoothScrolling() {
    document.querySelectorAll('.nav-link').forEach(link => {
        link.addEventListener('click', function(e) {
            e.preventDefault();
            const targetId = this.getAttribute('href').substring(1);
            document.getElementById(targetId).scrollIntoView({ 
                behavior: 'smooth' 
            });
        });
    });
}

// Mobile menu toggle
function setupMobileMenu() {
    const toggle = document.querySelector('.mobile-menu-toggle');
    const navUl = document.querySelector('nav ul');
    
    toggle.addEventListener('click', () => {
        navUl.style.display = navUl.style.display === 'flex' ? 'none' : 'flex';
    });
}

// Load initial gallery
function loadGallery() {
    const grid = document.getElementById('galleryGrid');
    grid.innerHTML = '';
    
    galleryStickers.slice(0, displayedStickers).forEach(sticker => {
        const card = createStickerCard(sticker);
        grid.appendChild(card);
    });
}

// Create sticker card element
function createStickerCard(sticker) {
    const card = document.createElement('div');
    card.className = 'sticker-card';
    card.innerHTML = `
        <div class="sticker-image">
            <span>${sticker.emoji}</span>
        </div>
        <div class="sticker-info">
            <h3>${sticker.prompt}</h3>
            <p class="sticker-prompt">${sticker.emoji} Generated by AI</p>
        </div>
    `;
    return card;
}

// Load more stickers
function loadMoreStickers() {
    const newCount = Math.min(displayedStickers + 4, galleryStickers.length);
    const grid = document.getElementById('galleryGrid');
    
    for (let i = displayedStickers; i < newCount; i++) {
        const card = createStickerCard(galleryStickers[i]);
        grid.appendChild(card);
    }
    
    displayedStickers = newCount;
    
    if (displayedStickers >= galleryStickers.length) {
        document.querySelector('.load-more-btn').style.display = 'none';
    }
}

// Scroll to generate section
function scrollToGenerate() {
    document.getElementById('generate').scrollIntoView({ behavior: 'smooth' });
}

// Set example prompts
function setPrompt(prompt) {
    document.getElementById('stickerPrompt').value = prompt;
}

// MAIN AI GENERATION FUNCTION - Works with FREE Hugging Face API
async function generateSticker() {
    const promptInput = document.getElementById('stickerPrompt');
    const prompt = promptInput.value.trim();
    
    if (!prompt) {
        alert('Please enter a description for your sticker!');
        promptInput.focus();
        return;
    }
    
    // Show loading
    document.getElementById('loadingSpinner').style.display = 'block';
    document.getElementById('stickerResult').style.display = 'none';
    
    try {
        // Use Hugging Face Inference API (FREE tier available)
        const animePrompt = `anime sticker of ${prompt}, cute chibi style, vibrant colors, clean lines, white background, sticker border, highly detailed, kawaii`;
        
        const response = await fetch(
            'https://api-inference.huggingface.co/models/nerijs/pixel-art-xl', 
            {
                method: 'POST',
                headers: {
                    'Authorization': 'Bearer hf_YourTokenHere', // Get free token at huggingface.co
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    inputs: animePrompt,
                    parameters: {
                        num_inference_steps: 20,
                        guidance_scale: 7.5,
                        width: 512,
                        height: 512
                    }
                })
            }
        );
        
        if (!response.ok) {
            throw new Error('API request failed');
        }
        
        const blob = await response.blob();
        const imageUrl = URL.createObjectURL(blob);
        
        // Display result
        document.getElementById('generatedSticker').src = imageUrl;
        document.getElementById('stickerResult').style.display = 'block';
        document.getElementById('loadingSpinner').style.display = 'none';
        
        currentGeneratedSticker = imageUrl;
        
    } catch (error) {
        console.error('Generation error:', error);
        
        // Fallback: Show placeholder with prompt
        document.getElementById('loadingSpinner').style.display = 'none';
        document.getElementById('stickerResult').style.display = 'block';
        
        const placeholderImg = document.getElementById('generatedSticker');
        placeholderImg.src = 'data:image/svg+xml;base64,' + btoa(`
            <svg width="300" height="300" xmlns="http://www.w3.org/2000/svg">
                <rect width="100%" height="100%" fill="#f0f0f0" rx="20"/>
                <text x="50%" y="50%" text-anchor="middle" dy=".3em" font-size="18" fill="#999">
                    ✨ ${prompt.substring(0, 30)}... ✨
                </text>
                <circle cx="50%" cy="30%" r="40" fill="#667eea"/>
                <text x="50%" y="35%" text-anchor="middle" dy=".3em" font-size="12" fill="white">AI</text>
            </svg>
        `);
        
        currentGeneratedSticker = placeholderImg.src;
    }
    
    // Auto-scroll to result
    document.getElementById('stickerResult').scrollIntoView({ behavior: 'smooth' });
}

// Download sticker
function downloadSticker() {
    if (!currentGeneratedSticker) return;
    
    const link = document.createElement('a');
    link.download = 'anime-sticker.png';
    link.href = currentGeneratedSticker;
    link.click();
}

// Share sticker
function shareSticker() {
    if (!currentGeneratedSticker) return;
    
    if (navigator.share) {
        navigator.share({
            title: 'My Anime Sticker!',
            text: 'Check out this awesome AI-generated anime sticker!',
            url: window.location.href
        });
    } else {
        // Fallback: Copy link
        navigator.clipboard.writeText(window.location.href);
        alert('Link copied to clipboard! Share it with friends 🎉');
    }
}

// Enter key support for generation
document.getElementById('stickerPrompt').addEventListener('keypress', function(e) {
    if (e.key === 'Enter') {
        generateSticker();
    }
});

// Animate elements on scroll
function animateOnScroll() {
    const cards = document.querySelectorAll('.sticker-card');
    cards.forEach((card, index) => {
        const rect = card.getBoundingClientRect();
        if (rect.top < window.innerHeight && rect.bottom > 0) {
            card.style.opacity = '1';
            card.style.transform = 'translateY(0)';
        }
    });
}

window.addEventListener('scroll', animateOnScroll);

// Add entrance animation to cards
document.querySelectorAll('.sticker-card').forEach((card, index) => {
    card.style.opacity = '0';
    card.style.transform = 'translateY(30px)';
    card.style.transition = 'all 0.6s ease';
});